application: y44y
version: 3
runtime: python
api_version: 1

handlers:
- url: /_zipme
  script: zipme.py

- url: /source.zip
  static_files: static/source.zip
  upload: static/source.zip 

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /bookmarklet
  static_files: static/bookmarklet.js
  upload: static/bookmarklet.js

- url: /canvas.html
  static_files: static/canvas.html
  upload: static/canvas.html

- url: /rpc_relay.html
  static_files: static/rpc_relay.html
  upload: static/rpc_relay.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /google343b6167050bcc8d.html
  static_files: static/google343b6167050bcc8d.html
  upload: static/google343b6167050bcc8d.html

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /xml
  static_dir: xml


- url: .*
  script: svgae.py
